### ISSUE TITLE
Проверка Tinkoff Generation

### ISSUE THREAD

**Issue by kryzhikov** [dz-015/GameOfLife#1]
🥺 или кто-то у кого-то списал, или списывали из одного источника, скорее второе, оба 0
https://github.com/barabekrb/gamefl

**Comment by dz-015** [comment]
Да, у нас с другом код действительно почти одинаковый получился. Мы основную часть проги вместе писали. Идею с квадратами я подкинул. Не списывали ниоткуда :(
